/* Given an array arr[] of N positive elements. 
* The task is to find the Maximum AND Value generated by any pair of element from the array.
* Note: AND is bitwise '&' operator. */

#include <bits/stdc++.h>
using namespace std;

// Utility function to check number of elements
// having set msb as of pattern

int checkBits(int pattern, int arr[], int n)
{

    int count = 0;

    for (int i = 0; i < n; i++)
    {

        if ((pattern & arr[i]) == pattern)
            count++;
    }

    return count;
}

int maxAND(int arr[], int n)
{

    int res = 0, count;
    for (int bit = 31; bit >= 0; bit--)
    {

        count = checkBits(res | (1 << bit), arr, n);

        if (count >= 2)
            res |= (1 << bit);
    }

    return res;
}

//Driver code

int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        int n;
        cin >> n;
        int arr[n + 5], i;

        for (i = 0; i < n; i++)
            cin >> arr[i];

        cout << maxAND(arr, n) << endl;
    }
    return 0;
}